function writeEdge(label,vIn,vOut,value,covariance,fileID)
%WRITEEDGE writes edge to graph file

covariance = covToUpperTriVec(covariance);
formatSpec = strcat('%s',...
                    repmat(' %d',1,numel(vIn)),...
                    repmat(' %d',1,numel(vOut)),...
                    repmat(' %.6f',1,numel(value)),...
                    repmat(' %.6f',1,numel(covariance)),'\n');
fprintf(fileID,formatSpec,label,vIn,vOut,value,covariance);
end

